### ISSUE TITLE
ignore flag request

### ISSUE THREAD

**Issue by FullStackForger** [joscha/indexifier#1]
`--ignore` flag would be super useful to for example avoid vendor and build folders

**Comment by fullstackforger** [comment]
Thinking of #2 and #3 perhaps there should be some sort of default ignore list. I am thinking of perhaps looking at `.gitignore` and basically applying those rules from within indexifier.

**Comment by fullstackforger** [comment]
Would you accept pull request?

**Comment by joscha** [comment]
Sorry, totally lost in my inbox - yes I would!

**Comment by fullstackforger** [comment]
Awesome. Will try to get into it ASAP

**Comment by cvan** [comment]
should I find myself with a minute, I'd love to add this too. I would recommend borrowing some of this logic: https://github.com/zeke/jus/blob/0441a9a6/lib/ignored.js

**Comment by fullstackforger** [comment]
Hey. Haven't forgotten about the issue but have been swamped at work last week or so. We should definitely get down to it at some point.

**Comment by joscha** [comment]
@fullstackforger are we still doing this? :)

**Comment by oncletom** [comment]
This feature would be super useful :-)

It seems to be supported by [directory-tree](https://github.com/mihneadb/node-directory-tree).

**Comment by joscha** [comment]
available as `3.1.0` //cc @oncletom @FullStackForger

**Comment by oncletom** [comment]
Amazing, thanks @joscha 👍
