### ISSUE TITLE
Package missing `version`

### ISSUE THREAD

**Issue by cvan** [joscha/indexifier#4]
I assume that's not intentional. Was curious why `semantic-release` script was there and `2.0.0` seems to be the latest release on `npm`, but the `package.json` in GitHub doesn't have `version`.

**Comment by joscha** [comment]
That is intentional. The versions are managed via `semantic-release`, tags and versions published on npm

**Comment by cvan** [comment]
Gotcha, thought so. Unfortunately, when doing patches, or using a fork, I can't install from a GitHub fork of mine via the command-line, like so:

```sh
npm install joscha/indexifier
```

I have to publish to npm to (temporarily) use a different version. There a way around this?

**Comment by joscha** [comment]
You can make the version number and all build generated output part of your
fork.

**Comment by cvan** [comment]
I would think other contributors would encounter the same issue, but understood.
