### ISSUE TITLE
Ambiguous flag "-h"

### ISSUE THREAD

**Issue by Zaijo** [joscha/indexifier#8]
Please - fix the help text of indexifier, because it states "-h" as both help and hml. I suggest removing the "-h" from help line.

**Comment by joscha** [comment]
Good catch, do you want to open a PR?

**Comment by Zaijo** [comment]
No.

**Comment by joscha** [comment]
I see. I will try and find some time to do it. I suggest you try and find some time to reflect on the opensource community, your interactions with that community and potentially improve communication patterns @Zaijo.

**Comment by Zaijo** [comment]
Well. I Changed my mind. Hope the PR does the job.
